"""
NAO Bridge Client

A Python client for the NAO Bridge HTTP API.
"""

from .client import (
    AnimationExecuteRequest,
    AnimationResponse,
    AnimationsListResponse,
    ArmsPresetRequest,
    AutonomousLifeRequest,
    BaseResponse,
    BehaviourDefaultRequest,
    BehaviourExecuteRequest,
    BehaviourResponse,
    BehavioursListResponse,
    DurationRequest,
    DurationResponse,
    HandsRequest,
    HeadPositionRequest,
    JointAnglesData,
    JointAnglesResponse,
    JointNamesResponse,
    LEDsRequest,
    LieRequest,
    NAOBridgeClient,
    NAOBridgeError,
    OperationResponse,
    OperationsResponse,
    PostureRequest,
    SequenceRequest,
    SequenceResponse,
    SonarData,
    SonarResponse,
    SpeechRequest,
    SpeedRequest,
    StatusData,
    StatusResponse,
    SuccessResponse,
    VisionData,
    VisionResolutionsResponse,
    VisionResponse,
    WalkPresetRequest,
    WalkRequest,
)

__version__ = "0.1.5"
__all__ = [
    # Main client
    "NAOBridgeClient",
    # Exceptions
    "NAOBridgeError",
    # Data models
    "StatusData",
    "SonarData",
    "VisionData", 
    "JointAnglesData",
    # Response models
    "BaseResponse",
    "StatusResponse",
    "SonarResponse",
    "VisionResponse",
    "JointAnglesResponse",
    "SuccessResponse",
    "DurationResponse",
    "OperationsResponse",
    "OperationResponse",
    "AnimationResponse",
    "AnimationsListResponse",
    "SequenceResponse",
    "VisionResolutionsResponse",
    "BehaviourResponse",
    "BehavioursListResponse",
    "JointNamesResponse",
    # Request models
    "DurationRequest",
    "PostureRequest",
    "SpeechRequest", 
    "WalkRequest",
    "HeadPositionRequest",
    "AutonomousLifeRequest",
    "SpeedRequest",
    "LieRequest",
    "ArmsPresetRequest",
    "HandsRequest",
    "LEDsRequest",
    "WalkPresetRequest",
    "AnimationExecuteRequest",
    "SequenceRequest",
    "BehaviourExecuteRequest",
    "BehaviourDefaultRequest",
]