"""
NAO Bridge Client Package

A modern Python client for the NAO Bridge HTTP API.
"""

from .client import (
    NAOBridgeClient,
    NAOBridgeError,
    # Request models
    DurationRequest,
    StandRequest,
    SitRequest,
    SpeedRequest,
    LieRequest,
    ArmsPresetRequest,
    HandsRequest,
    HeadPositionRequest,
    SpeechRequest,
    LEDsRequest,
    WalkStartRequest,
    WalkPresetRequest,
    AnimationExecuteRequest,
    SequenceRequest,
    AutonomousLifeRequest,
    BehaviourExecuteRequest,
    BehaviourDefaultRequest,
    # Response models
    ApiResponse,
    SuccessResponse,
    ErrorResponse,
    StatusResponse,
    SonarResponse,
    VisionResponse,
    VisionResolutionsResponse,
    JointAnglesResponse,
    JointNamesResponse,
    AnimationsListResponse,
    AnimationResponse,
    SequenceResponse,
    OperationsResponse,
    OperationResponse,
    DurationResponse,
    BehaviourResponse,
    BehavioursListResponse,
    # Data models
    StatusData,
    SonarData,
    VisionData,
    VisionResolutionsData,
    JointAnglesData,
    JointNamesData,
    BehavioursData,
    ErrorInfo,
)

__version__ = "1.0.0"
__all__ = [
    "NAOBridgeClient",
    "NAOBridgeError",
    # Request models
    "DurationRequest",
    "StandRequest", 
    "SitRequest",
    "SpeedRequest",
    "LieRequest",
    "ArmsPresetRequest",
    "HandsRequest",
    "HeadPositionRequest", 
    "SpeechRequest",
    "LEDsRequest",
    "WalkStartRequest",
    "WalkPresetRequest",
    "AnimationExecuteRequest",
    "SequenceRequest",
    "AutonomousLifeRequest",
    "BehaviourExecuteRequest", 
    "BehaviourDefaultRequest",
    # Response models
    "ApiResponse",
    "SuccessResponse",
    "ErrorResponse",
    "StatusResponse",
    "SonarResponse",
    "VisionResponse",
    "VisionResolutionsResponse",
    "JointAnglesResponse",
    "JointNamesResponse",
    "AnimationsListResponse",
    "AnimationResponse",
    "SequenceResponse",
    "OperationsResponse",
    "OperationResponse",
    "DurationResponse",
    "BehaviourResponse",
    "BehavioursListResponse",
    # Data models
    "StatusData",
    "SonarData", 
    "VisionData",
    "VisionResolutionsData",
    "JointAnglesData",
    "JointNamesData",
    "BehavioursData",
    "ErrorInfo",
]