name: Ruff
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Lint Python client
        uses: astral-sh/ruff-action@v3
        with:
          # only lint files under clients/python
          src: |
            clients/python
